include/MdLed.h
=> fix: type in MdLed.h

.editorconfig, .github/workflows/build.yml, .github/workflows/style-check.yml, tests/test_MdLed.cpp
=> GitHub Actionsにclang-formatとビルドチェックを追加する

.github/workflows/codeql.yml, .github/workflows/flawfinder.yml
**Issue**
- #14 
**対応内容**
CodeQL AnalysisをGitHub Actionsに追加して、自動セキュリティチェックを行う
**テスト**
workflowの追加なので、テストは必要なし
**残作業**
なし
=> add: codeql.yml #14

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/reinstall-cmake.sh, README.md
**Issue**
- #19
**対応内容**
Dev Container対応
**テスト**
開発環境に関する追加なので、テストは必要なし
**残作業**
なし
=> add: .devcontainer #19

.devcontainer/devcontainer.json
**Issue**
- #19
**対応内容**
.devcontainer.jsonに拡張機能を追記
**テスト**
環境の設定なので、テストは必要なし
**残作業**
なし
=> add: 開発に必要な拡張機能を.devcontainer.jsonに書いた #19

include/interfaceMotor.h, source/MdLed.cpp
**Issue**
- なし
**対応内容**
使っていない変数やinclude文があったので削除
**テスト**
特になし
**残作業**
なし
=> Remove unused includes and variables

CONTRIBUTING.md
**Issue**
- #38 
**対応内容**
CONTRIBUTING.md の追加
**テスト**
ドキュメントの追加なので、テストの必要なし
**残作業**
現状インターフェースクラスの命名規則が`interfaceXxxx`となっているので、それを`InterfaceXxxx` にする
=> add: CONTRIBUTING.md の追加 #38

include/A3921.h, include/InterfaceDigitalOut.h, include/InterfaceMotor.h, include/InterfacePwmOut.h, include/MdLed.h, source/A3921.cpp, source/MdLed.cpp, tests/stubs.h, tests/test_MdLed.cpp
**Isse**
- なし
**対応内容**
- State::Freeを削除
- ビルド時の警告(int と uintの比較)から修正
- static_castを使わない
- Doxygenコメントの追加/修正
**テスト**
外部仕様に変更はないため、追加したテストはなし
ただし、 State::Free の削除にともない、 State::Free の部分を State::Coast に変更した
また、static_castを使わないようにした関係で、そのあたりの処理も一部変えた
**残作業**
なし
=> fix: リファクタリング等軽い変更を実施した

include/MdLed.h, source/MdLed.cpp, tests/test_MdLed.cpp
**Issue**
- #46
**対応内容**
#46 に記載済み
**テスト**
Enum class名の変更だけなので、テストケースの修正はなし
**残作業**
とくになし
=> fix: Change class from Mode to BlinkMode #46

.devcontainer/Dockerfile, .gitignore, .vscode/settings.json, source/A3921.cpp, tests/test_A3921.cpp
**Issue**
- #49 
**対応内容**
#49 に記載の通り
**テスト**
A3921 の Reset 機能のテストを今まで SKIP していましたが、現在行える範囲で実施することにしました
その中でA3921のReset機能に問題が見つかったので修正し、それに伴ってテスト内容も変更しました
**残作業**
なし
=> Dev Contaier 用の設定を充実させる #49

include/A3921.h, source/A3921.cpp, tests/test_A3921.cpp
**Issue**
- #51
**対応内容**
タイトルの通り
**テスト**
暫定版だったA3921のReset機能のテストを正式版に修正した
**残作業**
特になし
=> update: A3921 の Reset 機能対応 #51

.devcontainer/devcontainer.json
**Issue**
- #58
**対応内容**
#58 の通り
**テスト**
Dev Containerの修正なので必要なし
**残作業**
なし
=> update: Dev Container の docker-in-docker を更新する #58

tests/test_A3921.cpp, tests/test_MdLed.cpp
**Issue**
- なし
**対応内容**
- テスト内の関数に static を付けた
- テスト内の bool を返す関数の構造を単純化
**テスト**
テストの内部的な構造を若干変更しましたが、
テスト自体の内容は変更していません
**残作業**
なし
=> update: いくつかの軽微な変更

include/A3921.h, include/MdLed.h, include/Motor.h, source/A3921.cpp, source/MdLed.cpp, tests/test_A3921.cpp, tests/test_Motor.cpp
**Issue**
- #79 
**対応内容**
#79 の通り
**テスト**
単純に言うと変数名を変更しただけなので、テストの追加等はなし
**残作業**
なし
=> update: デフォルト値をクラス内の構造体の中に定義する #79

.github/workflows/deploy-static.yml
**Issue**
- なし
**対応内容**
デプロイ時に指定するDoxyfileのパスを修正
**テスト**
ドキュメントの変更なのでなし
**残作業**
なし
=> fix: デプロイ時に指定するDoxyfileのパスを修正

.github/workflows/deploy-static.yml
**Issue**
- なし
**対応内容**
デプロイ時に指定するDoxyfileが生成するディレクトリのパスを修正
**テスト**
ドキュメントの変更なのでなし
**残作業**
なし
=> fix: デプロイ時に指定するDoxygenが生成するディレクトリのパスを修正

include/Id.h, source/Id.cpp, tests/test_Id.cpp
**Issue**
- #91
**対応内容**
- #92 対応時に漏れていたコメントを記載
**テスト**
ドキュメントの変更なのでなし
**残作業**
特になし
=> update: #92 で漏れていたコメントを記載

README.md
**Issue**
- #なし
**対応内容**
タイトルの通り
**テスト**
ドキュメントの変更のため、追加/変更の必要なし
**残作業**
なし
=> update: READMEのイメージ図を更新した

.github/workflows/build.yml, .github/workflows/cmake-test.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/style-check.yml
- #107 
#107 の通り
GitHub Actionsの変更だけなので必要なし
なし
=> update: GitHub Actionsの実行条件を絞る

include/CANMessage.h
- #14 
CANMessageクラスの説明文を追加した
なし
なし
=> update: CANMessageクラスの説明文を追加した

.github/workflows/build.yml, include/InterfaceDigitalOut.h, include/InterfacePwmOut.h, platform/mbed/include/MyDigitalOut.h, platform/mbed/include/MyPwmOut.h, platform/mbed/source/MyDigitalOut.cpp, platform/mbed/source/MyPwmOut.cpp, tests/stubs.h, tests/test_A3921.cpp, tests/test_MdLed.cpp
- #110
mbedの対応
内部処理は軽微であり、GitHub Actionsに組み込めないためなし
ただし、ビルドチェックは行う
=> add: Platformごとに基底クラスを継承したクラスを作成する #110

.github/workflows/build.yml, .github/workflows/cmake-test.yml, .github/workflows/codeql.yml, .github/workflows/style-check.yml
- #120 
- CMakeのテストをビルドのステップとテストのステップで分ける
- 各アクションの実行条件に、自身のアクションの変更時も追加する
- CMakeのテストをビルドのステップとテストのステップで分ける
- 各アクションの実行条件に、自身のアクションの変更時も追加する
なし
=> update: GitHub Actions #120

CMakeLists.txt, include/FakeUdpConverter.h, source/FakeUdpConverter.cpp, tests/CMakeLists.txt, tests/test_FakeUdpConverter.cpp
- #117
FakeUdp のビルドとテスト処理を追加する
FakeUdp のテストを実行するようにした
なし
=> fix: FakeUdp のビルドとテスト処理を追加する #117

.vscode/tasks.json
- #77
- Doxygen のビルド
- CMake での構成, ビルド, テスト
- Develop Containers のイメージのビルド
ソースコードの修正でないのでテストの追加・修正の必要はなし
細かく言えば #77 の残作業ではないが、 似たようなIssueの #78 は実施していない
=> update: VSCode のビルドタスクを構成した #77

.github/workflows/docker-image.yml
- #122
Develop Containersのイメージをビルドするアクションを追加した
アクションの追加なのでなし
なし
=> add: Develop Containersのイメージをビルドするアクションを追加した #122

.vscode/tasks.json
=> update: Development Containers用のビルドイメージをビルドするタスクを修正した

.github/workflows/build.yml, .github/workflows/cmake-test.yml
- なし
GitHub Actionsの対象外の漏れを修正
なし
なし
=> fix: GitHub Actionsの対象外の漏れを修正

doxygen/Doxyfile, doxygen/Doxyfile4GeneralUsers
- なし
Doxygenでplatformディレクトリのファイルのドキュメントを出力するようにした
なし
なし
=> update: Doxygenでplatformディレクトリのファイルのドキュメントをサポートする

doxygen/Doxyfile, doxygen/Doxyfile4GeneralUsers, doxygen/index.md
- #130
Doxygen 用のメインページを追加した
ドキュメントの修正なので、変更の必要はなし
なし
=> add: Doxygen 用のメインページを追加した #130

README.md
=> update: README.md に利用例を追加

tests/CMakeLists.txt, tests/integration_test.cpp
=> add: デューティー比と回転方向のデータをやり取りする統合テストを追加した

include/CANMessage.h, include/FakeUdpConverter.h, include/PwmDataConverter.h
- #135
タイトルの通り
ドキュメントの変更なので、追加/変更は必要ない
なし
=> update: Doxygen の @param [in] と [out] を利用した #135

README.md, doxygen/Doxyfile, doxygen/Doxyfile4GeneralUsers, images/icon.svg
- #130
以前 #130 で `doxygen/index.md` を追加してメインページ化を試みたが、設定のミスで表示されなかった
そのため、メインページの設定を修正する
また、メインページとするページを `doxygen/index.md` から `README.md` に変更する
なし
なし
=> fix: メインページが表示されなかった不具合を修正した #130

.github/workflows/deploy-static.yml
理由: Doxygenの生成するページでSVGの透過を発生させたいため
- なし
タイトルの通り
なし
なし
=> update: deploy時のDoxygenのバージョンを変更した

include/FakeUdpConverter.h, include/PwmDataConverter.h
=> update: 関数の返り値の詳細をドキュメントに記載した

.mbedignore, include/InterfaceDigitalOut.h, include/InterfacePwmOut.h, include/MdLed.h, tests/integration_test.cpp, tests/test_SpeedDataConverter.cpp
- なし
いくつかの他の機能に影響のない修正を行った
なし
なし
=> update: いくつかの軽微な修正

doxygen/index.md
=> delete: 使われていない doxygen/index.md を削除した

include/Motor.h, include/SpeedDataConverter.h, source/Motor.cpp, tests/test_Motor.cpp
- #140
- #140
- SpeedDataConverterクラスの説明を追加した
追加した関数のテストを行った
なし
=> update: MotorクラスにPWM制御をしたいのか、速度制御をしたいのかわかるような値を持たせた #144

tests/test_Error.cpp, tests/test_FakeUdpConverter.cpp, tests/test_Id.cpp, tests/test_Motor.cpp
- なし
- testing::internal::GetCapturedStderr().c_str(); から .c_str() を削除
- test_Motor.cpp のテストでエラー表示がされていたが抑制した
対応内容と同じ
なし
=> update: テストを修正した

source/A3921.cpp, source/Error.cpp, source/FakeUdpConverter.cpp, source/Id.cpp, source/MdLed.cpp, source/Motor.cpp, source/PwmDataConverter.cpp, source/SpeedDataConverter.cpp, source/bit.cpp, tests/integration_test.cpp, tests/test_Error.cpp, tests/test_Motor.cpp
=> fix: Mbed Studioのビルドエラーを修正 #149

.vscode/tasks.json, include/DataConverter.h, source/A3921.cpp, source/Error.cpp, source/FakeUdpConverter.cpp, source/Id.cpp, source/MdLed.cpp, source/Motor.cpp, source/PwmDataConverter.cpp, source/SpeedDataConverter.cpp, source/bit.cpp, tests/test_A3921.cpp, tests/test_Id.cpp, tests/test_MdLed.cpp
- なし
テストの説明を修正 & message_base -> message_format
なし
なし
=> update: テストの説明を修正 & message_base -> message_format

source/CANMessage.cpp, source/MdLed.cpp
=> update: 一目見て理解できるように基本的に 大なり(>) になっている部分を小なり(<)に変更

source/Id.cpp
- なし
- motor_is_valid の引数を交換した
- get_motor_id の引数の順番と揃えるため
- エラーチェックをまとめた
なし
なし
=> update: Id.cpp

source/PwmDataConverter.cpp, source/SpeedDataConverter.cpp, tests/test_PwmDataConverter.cpp, tests/test_SpeedDataConverter.cpp
- なし
SppedDataConverter::decode(), PwmDataConverter::decode()の時に、それぞれヘッダ部分のチェックを行うようにした
エラーチェックができているかのテストを追加した
なし
=> update: デコード時にヘッダ部分を確認した

tests/integration_test.cpp
=> update: 結合テスト部を速度制御に対応させた #167

source/MotorDataConverter.cpp
- なし
以下と同じ
- #149
- #150
なし
なし
=> fix: Mbed Studioでのビルドエラーを修正

include/Motor.h, include/adjust_duty_cycle.h, source/Motor.cpp, tests/CMakeLists.txt, tests/test_adjust_duty_cycle.cpp
=> update: 徐々にデューティ比を変化ができるようにした #173

tests/test_adjust_duty_cycle.cpp
なし
- 目標のデューティー比が最終的にモータに反映されることを確認するテストを追加
- 変数名の誤字を修正(nest_xx -> next_xx)
対応内容と一緒なので省略
なし
=> update: テスト項目を追加

include/Motor.h
- #187
double型からfloat型にするために接尾辞(F)をつけた
=> double型からfloat型にした

source/Error.cpp, source/Id.cpp
- #190
sprintf() を利用している箇所を sprintf() を利用しないようにした
外部仕様は変化しないため、テストの追加は必要なし
=> fix: sprintf() を利用しない #190

include/MdLed.h, source/MdLed.cpp
- なし
- MdLed の BlinkMode の優先度をコメントに残した
- ヘッダ(宣言)とソース(実装)で MdLed::mode() の仮引数の名前が異なっていたので修正した
- MdLed::write() の仮引数を type から value に変更した
テストは変更なし
なし
=> update: MdLed の BlinkModeの優先度をコメントで記載した

include/mutex.h, spirit.h, tests/integration_test.cpp
- #179
- #197
- 全てのヘッダをインクルードする spirit.h を作った
- 結合テスト(tests/integration_test.cpp)でインクルードするヘッダをspirit.hに変更した
- mutex.h のインクルードを修正した
対応内容に記載した結合テストのインクルードファイルを変更した点のみ
新規作成したヘッダファイル(spirit.h)が必要なファイルをインクルードしていることを確認するため変更した
なし
=> update: spirit.h を作成した #179 #197

source/A3921.cpp, source/FakeUdpConverter.cpp, source/Id.cpp, source/MdLed.cpp, source/Motor.cpp, source/MotorDataConverter.cpp, source/PwmDataConverter.cpp, source/SpeedDataConverter.cpp, source/bit.cpp, tests/test_SpeedDataConverter.cpp
- なし
Errorクラスのインスタンスの作成・利用方法を変更した
機能仕様に変更がないため、テストも変更なし
なし
=> update: Errorクラスのインスタンスの作成・利用方法を変更した

doxygen/Doxyfile, doxygen/Doxyfile4GeneralUsers
=> fix: arduino対応のディレクトリ構造に対応していなかった問題を修正した

doxygen/Doxyfile, doxygen/Doxyfile4GeneralUsers
=> add: spirit.hをDoxygenの対象に追加した

.github/workflows/deploy-static.yml, .github/workflows/doxygen.yml
- なし
Doxygenの動作までテストに組み込みたかったため、本テストを追加した
テストの実行条件にPull requestを追加し、デプロイはPull requestで行わないようにした
なし
=> update: コンテンツの生成までを行うテストをPullRequestで行う

.github/workflows/deploy-static.yml, .github/workflows/doxygen.yml
=> fix: デプロイに失敗する問題を修正した

.github/workflows/deploy-static.yml
=> fix: アクションの再利用をしていたが、生成したコンテンツを再利用できないため元に戻した

.github/workflows/deploy-static.yml
=> fix: runs-onの指定し忘れを修正した

.github/workflows/style-check.yml
- #218
Issueの通り
リポジトリ直下のspirit.hもあるため、リポジトリ全体をフォーマット対象にする
なし
なし
=> fix: フォーマット対象のディレクトリ指定のミスを修正 #218

.github/workflows/build.yml, src/spirit/include/mutex.h, src/spirit/src/mutex.cpp
- #211
ArduinoのSTM32に対応した
arduino-cliでSTM32のボード用のコンパイルテストを追加した
なし
=> update: ArduinoのSTM32対応をした #211

.github/workflows/build-mbed/main.cpp, .github/workflows/build.yml
- #214
タイトルの通り
ビルドするメインファイルをspirit.hをインクルードしてspiritを利用するものに変更した
なし
=> update: mbedのテストのmain.cppをspirit.hを使うように変更した #214

src/spirit.h, src/spirit/platform/arduino/include/DigitalOut.h, src/spirit/platform/arduino/include/PwmOut.h, src/spirit/platform/arduino/src/DigitalOut.cpp, src/spirit/platform/arduino/src/PwmOut.cpp
- #110
タイトルの通り
なし
- #223
- #229
=> update: platformをArduinoに対応させた #110

.github/workflows/build.yml, CMakeLists.txt, src/spirit.h, src/spirit/include/mutex.h, src/spirit/platform/mbed/include/DigitalOut.h, src/spirit/platform/mbed/include/PwmOut.h, src/spirit/platform/mbed/source/DigitalOut.cpp, src/spirit/platform/mbed/source/PwmOut.cpp, src/spirit/src/mutex.cpp
- #220
ArduinoのMbed(Picoなど)に対応した
Arduino CLIのビルド対象にpicoとenvie_m7を追加した
なし
=> update: ArduinoのMbedに対応した #220

src/spirit/include/Error.h, src/spirit/src/A3921.cpp, src/spirit/src/Error.cpp, src/spirit/src/FakeUdpConverter.cpp, src/spirit/src/Id.cpp, src/spirit/src/MdLed.cpp, src/spirit/src/Motor.cpp, src/spirit/src/MotorDataConverter.cpp, src/spirit/src/PwmDataConverter.cpp, src/spirit/src/SpeedDataConverter.cpp, src/spirit/src/bit.cpp, tests/test_Error.cpp, tests/test_Motor.cpp
- #241
Issueの通り
- 一部のテストで異常系のテスト時に標準エラー出力をキャプチャしていなかったので修正した
なし
=> feat: error()とwarning()を変更 #241

src/spirit/include/Motor.h, src/spirit/include/SpeedDataConverter.h, src/spirit/src/Motor.cpp, src/spirit/src/SpeedDataConverter.cpp, tests/integration_test.cpp, tests/test_Motor.cpp, tests/test_MotorDataConverter.cpp, tests/test_SpeedDataConverter.cpp
=> refactor: Kp, Ki, Kdをkp, ki, kdに変更

tests/test_A3921.cpp, tests/test_Motor.cpp
=> refactor: テストコードを改善

.cspell.json, .devcontainer/devcontainer.json
=> chore: Devcontainerでビルド済みイメージを利用する #250

.devcontainer/Dockerfile, .github/workflows/devcontainer.yml
=> chore: インストールするnodejsのバージョンを最新のLTSに変更 #252

.devcontainer/Dockerfile, .devcontainer/script/install-gcc-arm-none-eabi.sh
=> chore: GNU Arm Embedded Toolchain のインストールスクリプトを改善

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
- なし
- name を変更
- gitconfig をローカルからコンテナにコピーするように変更
なし
なし
=> chore: Dev containerを改善

src/spirit/include/bit.h, src/spirit/src/PwmDataConverter.cpp, src/spirit/src/SpeedDataConverter.cpp, src/spirit/src/bit.cpp, tests/test_bit.cpp
- #249
- Issueの通り
- `bit.h`に関係するコメントとテストを改善
=> feat: get_range_value() の入出力を改善し、エラー時と出力を分離 #249

.github/workflows/build.yml
=> chore: ビルドディレクトリへの移動するコマンドを変更 #259

.github/workflows/actionlint.yml
- なし
GitHub　ActionのワークフローのファイルのLinterであるActionlintを使うワークフローを追加した。
なし
なし
=> chore: add Actionlint workflow

src/spirit/src/bfloat16.cpp
- なし
機能や入出力に変更のない範囲で処理の改善をした
なし
なし
=> style: 仮数部のけち表現まわりの処理をわかりやすいように修正

src/spirit/include/adjust_duty_cycle.h, tests/test_adjust_duty_cycle.cpp
- #186
タイトル通り。
追加したエラーチェックのテストを追加した。
#186 の今回対応していない機能。
=> feat: adjust_duty_cycle() の state の範囲チェックを追加 #186

src/spirit/include/Motor.h
=> feat: ゲインの初期値を暫定値から更新

src/spirit/include/SpeedController.h, src/spirit/src/SpeedController.cpp, tests/test_SpeedController.cpp
=> fix: rpsが正しく算出されていない問題の修正とrpsを参照可能に変更 #281

tests/test_A3921.cpp, tests/test_Motor.cpp, tests/test_SpeedController.cpp
=> test: 正常系のテスト中にエラーが発生していないことを確認

.cspell.json, .github/dependabot.yml
=> chore: add dependabot.yml

.github/dependabot.yml
- #xx
depandabot が作成する pull request はデフォルトでレビュワーが設定されていないため、レビューが必要なのかタスクなどに登録されず見つけにくい。
自動でレビュワーを設定することで、必要なこととしてわかりやすくする
なし
なし
=> chore: depandabot の pull request のレビュワーを設定

.github/dependabot.yml
- なし
https://github.com/yutotnh/spirit/runs/16879173581 に記載のエラーを修正した。
なし
なし
=> fix: reviewers のエラーを修正

README.md
=> docs: CodeFactorのステータスバッジを追加

.github/workflows/actionlint.yml, .github/workflows/build.yml, .github/workflows/cmake-test.yml, .github/workflows/codeql.yml, .github/workflows/devcontainer.yml, .github/workflows/doxygen.yml, .github/workflows/spell.yml, .github/workflows/style-check.yml
=> test: どのブランチでもPush時にテストが走るようにする #305
