README.md

GitHub Codespacesの環境では ctest の `--test-dir` オプションが利用できなかった（2022/11/09 現在） 
多くの人がGitHub Codespacesで開発することを考慮して、`--test-dir`オプションを利用しない手順に変更した

update: テスト実行手順を変更

---

tests/stubs.h

**Issue**
- なし
**対応内容**
`stub.cpp`内のクラスのメンバ変数を初期化していなかったので、初期化した
**テスト**
Stubなので特になし
**残作業**
なし

fix: Initialize member variables of `stub.cpp`

---

source/A3921.cpp
tests/stubs.h
tests/test_A3921.cpp

**Issue**
- なし
**対応内容**
A3921のパルス周期に着目したテストを追加しました
また、必要なテストの追加に伴い実装にいくつか手を加えました
- `StubPwmOut` クラスにパルス周期を得る `read_period()` を追加
- A3921の初期化時に、パルス周期を設定する
- `A3921::pulse_period()` 中で、PHASEピンにパルス周期を設定する
**テスト**
以下のテストを追加した
- A3921の初期化時にパルス周期を意図した値で設定しているかのテスト
- `A3921::pulse_period()` でPWMHピン、PWMLピン、PHASEピンのパルス周期が変わっていることのテスト
**残作業**
特になし

Add: A3921のパルス周期に着目したテストを追加する

---

source/A3921.cpp

**Issue**
- #35
**対応内容**
Issueで提案した範囲チェックの廃止を行いました
**テスト**
範囲チェックを行っているか/行っていないかの確認はわざわざすることではないと思うので、行っていません
また、テスト用のスタブもMbedのようにデューティー比が1.00より多ければ1.00にする必要もないと判断した
**残作業**
なし

update: Eliminate duty ratio range checks

---

source/A3921.cpp
tests/test_A3921.cpp

**Issue**
- #37 
**対応内容**
SlowDecayのPWMをHigh sideからLow sideに変更
**テスト**
PWMをかける場所がHigh sideからLow sideに変更になったため確認内容を変更
**残作業**
汎用性を持たせるためPWMをかけるサイドを切り替える機能の実装

changes:Slow DecayのPWMをlow sideに変更#37

---

include/A3921.h
source/A3921.cpp
tests/test_A3921.cpp

**Issue**
- #44 
**対応内容**
Slow decay のPwm side を切り替える機能の追加。
**テスト**
slow decay のテストをLow side と High side 用で分けて作成
**残作業**
#include <gtest/gtest.h>が通らず、テストの実行が出来ないため確認お願いします。

Add:Slow decay のPwm side を切り替える機能の追加。

---

include/InterfaceMotor.h
source/A3921.cpp
tests/test_A3921.cpp

**Issue**
軽微な修正なのでなし
**対応内容**
- include/InterfaceMotor.h
- default_pulse_period の値をわかりやすい表に気変更
- source/A3921.cpp
- 接尾辞のUがついているものがあったので、削除
- tests/test_A3921.cpp
- isBrake() → is_brake()
- isCoast() → is_coast()
**テスト**
構造に変化を及ぼさないのでなし
**残作業**
なし

fix: いくつかの軽微な修正

---

.vscode/settings.json

**Issue**
- なし
**対応内容**
User や Remote にFileEncoding の設定があると、本リポジトリ内はすべてUTF-8であるにもかかわらず、そちらの設定が優先されてしまう。
そのため、最優先となる Work space で UTF-8 に設定することで、上記の問題が発生しないようにする
**テスト**
設定の変更なので、テストの追加/変更の必要なし
**残作業**
特になし

update: Encoding を UTF-8 にする設定を追加

---

.github/workflows/deploy-static.yml

**Issue**
- なし
**対応内容**
以下のPullRequestで`doxygen-awesome-css`をサブモジュールとして追加したが、[deploy-static.yml](https://github.com/yutotnh/spirit/blob/main/.github/workflows/deploy-static.yml)が失敗するようになってしまった
アクション内でサブモジュールを持ってくる設定を行い、デプロイに成功させる
- #81
**テスト**
ドキュメントの変更なのでなし
**残作業**
なし

Fix: deploy時にsubmoduleを持ってくる

---

CMakeLists.txt
include/Id.h
source/Id.cpp
tests/CMakeLists.txt
tests/test_Id.cpp

**Issue**
- #91
**対応内容**
CAN通信の場合のIDを返す関数を追加した
**テスト**
`can::get_motor_id` の各引数に着目したテストを追加
**残作業**
SPI, I2Cの場合の取り決め

update: CAN通信の場合のIDを返す関数を追加した  #91

---

README.md

**Issue**
- #97 
**対応内容**
- READMEのGitHub Pagesへのリンクが切れている問題を修正
- Build & Test の例の言語をshellにして、シンタックスハイライトを有効にした
**テスト**
ドキュメントの修正なのでなし
**残作業**
なし

update: READMEの改善 #97

---

include/FakeUdpConverter.h
include/PwmDataConverter.h
source/FakeUdpConverter.cpp
source/PwmDataConverter.cpp
tests/test_FakeUdpConverter.cpp
tests/test_PwmDataConverter.cpp

- #113
タイトルの通り
- 「ビット幅の節約のために、既存のバッファの幅の精度をbyteからbitにする」に伴ってPwmDataConverterのテストを修正
- FakeUdpのテスト用を新規作成

update: トランスポート層相当のレイヤーを追加する(UDP)

---

CMakeLists.txt

- なし
https://github.com/yutotnh/mbed-can-motor-driver-for-spirit で本ライブラリをビルドしたらエラーになった
そのエラーを回避するための修正が入っている
本修正はほかのプロジェクトからビルドされたときにはじめて意味が分かる
- #112

fix: 他のプロジェクトがmbedのライブラリとして利用した時にビルドエラーとなる問題を修正

---

include/Error.h
source/A3921.cpp
source/Error.cpp
source/FakeUdpConverter.cpp
source/Id.cpp
source/MdLed.cpp
source/Motor.cpp
source/PwmDataConverter.cpp
source/SpeedDataConverter.cpp
source/bit.cpp
source/mutex.cpp

- #151
#151 のビルドエラーの原因は、NUCLEO_F303K8 のデフォルトの設定では軽量版のライブラリが用いられていることだった
そのライブラリでは std::string で特定の文字列操作を行う場合リンクエラーが発生する
文字列操作は snprintf を利用した文字列操作を行うことにすればビルドエラーが発生しなくなるため、 std::string を利用している箇所を snprintf を利用した文字列操作に変更する
内部処理の変更のため、変更の必要なし
なし

fix: std::string を使わないように変更

---

CMakeLists.txt
include/mutex.h

- mbed-tools のビルドエラー(https://github.com/yutotnh/mbed-can-motor-driver-for-spirit/pull/11) を修正

fix: mbed-tools のビルドエラーを修正

---

source/A3921.cpp

brakeが一定方向にしかかからない問題を修正するため、rsを1に設定した。

ffix:brakeが一定方向にしかかからない問題を修正

---

tests/CMakeLists.txt

- なし
カバレッジ分析ができるように `tests/CMakeLists.txt` のコンパイルオプションを追加した。
参考: https://qiita.com/imasaaki/items/0021d1ef14660184f396
あとは、以下のような手順でカバレッジを確認できる
```console
$ cd biuld/tests
$ lcov -d . -c -o coverage.info
$ lcov -r coverage.info */googletest/* test/* */c++/* -o coverageFiltered.info
$ genhtml -o lcovHtml --num-spaces 4 -s --legend coverage.info
```
なし

update: カバレッジ分析ができるようにオプションを追加

---

include/adjust_duty_cycle.h
source/Motor.cpp
tests/test_adjust_duty_cycle.cpp

- #180
- 機能変更: adjust_duty_cycle の Motor クラスの引数の部分をデューティー比、回転方向、上昇の最大値、下降の最大値に変える
-  速度制御時は、Motorクラスでは目標値を持っていないため、引数を変更する必要がった
- バグ修正: 以下の部分が下降のChengeLevelのみ見ていたのが原因で、 motor.change_level(Motor::ChangeLevelTarget::Fall, Motor::ChangeLevel::OFF) のとき、回転方向を変える際上昇のChangeLevelを無視して回転方向とデューティー比をすぐに目標値を設定するようになっていたバグを修正
https://github.com/yutotnh/spirit/blob/62dd6467d199d7455a4ade670a203816b6d399a1/include/adjust_duty_cycle.h#L25-L30
本修正でテスト対象の引数と動作が変化したので、修正した
テストも、様々な組み合わせで最終的にデューティー比へ到達することを確認するものを追加した
異常系の制御の追加やテストの追加は #186 で対応する

update: adjust_duty_cycle() を速度制御対応させる #180

---

include/Error.h
include/Motor.h
source/Error.cpp
source/Motor.cpp
tests/test_Error.cpp
tests/test_Motor.cpp

- #185
Issueに記載の内容 + Errorの修正
Erorrの修正内容
今までエラー状態が一度WarningやErrorになったらNormalに戻ることがなかったので、Normalに戻すようにしてテストケースごとにきちんとエラー状態がNormalからError(Warning)になることを確認する
- Errorに追加した関数(reset)用のテストを追加
- spirit::Motor::ChangeLevel::Manual で設定可能な最小値を下回ったらエラーを出力することを確認するテストを追加

spirit::Motor::ChangeLevel::Manual で設定可能な最小値を下回ったらエラーを出力する

---

tests/integration_test.cpp
tests/test_PwmDataConverter.cpp
tests/test_adjust_duty_cycle.cpp

- なし
- AdjustDutyCycle.Normal のテスト時間を約1/4に縮小した
- コンパイラが出す警告を減らした
- テストコード自体は変更したが、テストケースに関しては変更していない

update: テスト時間の短縮 & コンパイラによる警告を減らす

---

.github/workflows/build-mbed-tools/CMakeLists.txt
.github/workflows/build.yml

- #112
Issueの記載の通り
今まで `build-mbed-tools` では mbed-os のみビルドしていたが、 spirit もビルドするようにした
なし

fix: spiritライブラリを Mbed CLI 2 でビルドしていない問題を修正した #112

---

CMakeLists.txt
include/mutex.h
spirit.h

- なし
マクロ定義されているかを if のみから、 if + defined で確認する
マクロ定義されているかを意図した処理のため、より意図に近い if + defined にした
また、今回の問題が原因で定義していた SPIRIT_MBED マクロの定義を削除した
なし
なし

fix: マクロ定義されているかを if のみから、 if + defined で確認する

---

README.md

- なし
タイトルの通り
恐らく今まで、`main`ブランチ以外でActionがフェイルしたときに、README.mdに記載しているステータスバッジに反映される場合があった
なし
なし

update: ステータスバッジを表示するブランチを"main"に統一した

---

.github/workflows/build.yml

元々GitHub Actionsでは終了ステータスが0以外だと、ワークフロー終了する
`set -e`も同様のことをする目的で実行しているため必要ない
- なし
タイトルの通り
`set -e`を削除した
なし

fix: 不必要な`set -e`を削除した

---

src/spirit/include/Motor.h
src/spirit/src/Motor.cpp
tests/test_Motor.cpp
tests/test_adjust_duty_cycle.cpp

- なし
- もともと change_level() の一部であった処理を maximum_change_duty_cycle() に変更
- 主に速度制御用の関数に仮引数の範囲チェックがなかったので追加した
- 追加した関数のテスト
- 追加した範囲チェックのテスト
なし

feat: maximum_change_duty_cycle() と各関数の引数の範囲確認を追加

---

src/spirit/src/bfloat16.cpp
tests/test_bfloat16.cpp

- #247
負の正規化数の場合に意図しない数値になっていたバグを修正した
負の正規化数の場合に意図しない数値になっていることを確認するテストを追加した
なし

fix: 負の正規化数の場合に意図しない数値になっていたバグを修正 #247
